### PR TITLE
BL-390 Updated Techstack visualization notebook idea

### PR DESCRIPTION
**Pull request by marthabg**
## Description
Co-authors: Olivia Peterschmidt, Jason Gersing, Cristian Ibarra-Villegas, Martha Gonzalez

This notebook is meant to be an update to the tech-stack_visualization notebook found in the notebooks folder that was used to create the graph in the graph.py file. We figured it would be much more useful to visualize tech stacks of mentors and mentees side by side instead of consolidated together as shown by the previous tech_stack_visualization.ipynb notebook. Digging deeper we saw that in order to get to a comfortable point to play with the techstack datasets, we had to do some data engineering and then from there could experiment with altair. Scroll all the way to the bottom to view the final visualization.

Fixes # BL-390

## Type of change

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes
https://www.loom.com/share/924422932cca4226a13283369b560e6e

### CODE REVIEW

**Review by annakoduru6 — APPROVED** [review]
Easy to compare mentor and mentee compatibility side by side. Good idea!

**Review by sspradling78 — APPROVED** [review]
I definitely like these graphs more than the ones previous, good job. I approve.

**Review by bradwbaker — APPROVED** [review]
Easy to see the similarities of mentors tech stack with what the mentees want. The altair visualizations were done very nicely!

**Review by sujatasahoo — APPROVED** [review]
Good visualization on tech-stack of mentors and mentees side by side. Definitely helpful.

**Review by BrokenShell — CHANGES_REQUESTED** [review]
Please update how you access the mongo url to use dotenv library and the .env file rather than hard code the password into a public notebook.

**Review by BrokenShell — APPROVED** [review]

**Pull request merged**
