### PR TITLE
fixes model signature for type mismatch

### PR DESCRIPTION
**Pull request by ev-horrosh**
## Description

fixes model signature for type mismatch
@BrokenShell 

- [x] Bug fix

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by BrokenShell — APPROVED** [review]
Yes! Great job.

**Review by ulloa — APPROVED** [review]
Accurately addresses the mismatched types.

**Review by ZacharyRock — APPROVED** [review]
Good work on also updating the call docstring to more accurately reflect what the function needs and does.

**Review by OlatomiAdigun — APPROVED** [review]
Nice, updating the mismatched types.

**Pull request merged**
