### PR TITLE
BL-488—Feature/mentee generators update

### PR DESCRIPTION
**Pull request by opeterschmidt**
## Description

Co-authors: Austin Wood, Sayer Kanakriyeh, Olivia Peterschmidt

Updates `RandomMentee` class in `user_generators.py` to correspond with the latest schema, as part of the in-progress database architecture overhaul. Added new attributes as necessary and ensured attribute data types met revised schema requirements.

_Note: user_generators.py file name to be updated as part of subtask BL-497_

Fixes [BL-488](https://bloomtechlabs.atlassian.net/browse/BL-488?atlOrigin=eyJpIjoiNDE1NDE4NDc0ZmMxNGFiM2IyYjM3Y2MxMjI3MWM0ZWMiLCJwIjoiaiJ9) (subtask: BL-485)

[Loom Video](https://www.loom.com/share/10176cbd61c2499d8f3b80482d95daf1)
## Type of change

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by ErinNC — DISMISSED** [review]
Nice job! The 21 fields here match the architecture spreadsheet and the mentee model.

**Review by sspradling78 — DISMISSED** [review]
Looks good, approved by me.

**Review by annakoduru6 — APPROVED** [review]
Good job, seems like everything is consistent with the schema

**Review by rogerfvieira — APPROVED** [review]
Great update. Very smart to keep the data generators consistent with the new database architecture.

**Review by jsgersing — APPROVED** [review]
Good work! This update to the user_generators (now generators) file is consistent with the changes in the schema file.

**Review by sujatasahoo — APPROVED** [review]
Nice update on RandomMentee class.

**Review by CrisIV — APPROVED** [review]
Great job keeping the data generators consistent with the schema updates.

**Review by bradwbaker — APPROVED** [review]
Good job, changes look good with updated schema

**Review by willisbridges — COMMENTED** [review]
Well done, changed per discussions and excel sheet

**Review by willisbridges — APPROVED** [review]

**Review by L0lbrich — APPROVED** [review]
Like Willis mentioned we should change the date times to be random date times instead of current date times. Im not going to request this change here because there are other places this needs to be changed and Steven is going to create a git issue for it. Otherwise looks great!

**Review by marthabg — APPROVED** [review]
I don't really see the point in changing the convictions line of code, but it still works so no complaints here!

**Pull request merged**
