### PR TITLE
Adds computer assignment components

### PR DESCRIPTION
**Pull request by ZacharyRock**
## Description

This adds the computer assignment components to the API and MongoDB class, as well as the computer assignment file necessary for them.  It assigns assignment ratings to mentees put into the "computer_assignment" cluster, and it adds an API get request for an HTML table for easy visualization by frontend.  HTML table was chosen so frontend could easily add clickable components to help with the rest of the computer assignment workflow.
Note:  this feature was formerly known as "computer matching", but that was shown to cause confusion among front/backend between matching components, resource components, and this separate component, so "assignment" was chosen as a unique, easily identifiable namespace.  

https://www.loom.com/share/a6bcc325931348ebaad1193ba30bae0b

## Type of change

- [x] New feature
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by hollberg — COMMENTED** [review]
Looks like a good start. My IDE throws a warning because numpy is not in the requirements.txt file. Could you update that as well?

**Comment by ZacharyRock** [comment]
> Looks like a good start. My IDE throws a warning because numpy is not in the requirements.txt file. Could you update that as well?

Done, thanks for the catch!

**Review by hollberg — APPROVED** [review]
Really nice new endpoint, and great work updating the Mongo model and developing the helper functions to support it. Good call to output an HTML table for the Front-end folks; should be easy for them to use. And thanks for updating the requirments.txt so quickly!

**Review by mgrohnke — APPROVED** [review]
This looks great - incredible work!

**Comment by BrandonSmith710** [comment]
Cool stuff, allocation of resources like computers will be fundamental in keeping the mentees as empowered as possible.

**Review by BrandonSmith710 — APPROVED** [review]
Cool stuff, allocation of resources like computers will be fundamental in keeping the mentees as empowered as possible.

**Pull request merged**
