### PR TITLE
Bl 841 ds update how we generate uui ds

### PR DESCRIPTION
**Pull request by randynobx**
## Description
- Replaces all `generate_uuid(16)` calls with `uuid.uuid4()` random uuid generator call
- Sets `app/schema.py` max_length constraints to 36 for relevant id fields.
- Removes `generate_uuid` function and orphaned imports

## Jira Ticket
[BL-841](https://bloomtechlabs.atlassian.net/browse/BL-841)

## Type of Change
- [x] New feature

## Checklist
- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

## Loom Video
[Loom Video](https://www.loom.com/share/48e593f559c249a9b71f1fa042cfcdfe)

### CODE REVIEW

**Review by jtorres03 — APPROVED** [review]
Nice! I was looking at this working on this one a while back, and glad to see someone tackled it. Looks good. I think the only thing i noticed was no loom video. I could be mistaken but I didn't see it under the loom heading.

**Comment by randynobx** [comment]
@jtorres03 Loom video is coming!

**Comment by BrokenShell** [comment]
This is fantastic, I have no notes. You even removed the unused libraries from the imports. Great work! Did you reseed the database?

**Comment by randynobx** [comment]
> Did you reseed the database?

I have not reseeded the database yet. I wanted to get some eyes on the changes before I did that.
I can reseed it this evening.

**Comment by randynobx** [comment]
@BrokenShell Reseeding is being blocked by the issue I noted in Issue #246. I'll drop in during office hours tomorrow to discuss (it coincidently is semi-related to the other ticket that I grabbed).

**Review by nikolayglushetskiy — APPROVED** [review]
Everything looks fine!

**Comment by JeffDesch** [comment]
Combined with the change/bugfix in BL-965 the database should be good to reseed after this is pulled. Changes look clean.

**Comment by randynobx** [comment]
Database is now reseeded.

**Pull request merged**
