### PR TITLE
BL-136/BL-393 Create Feedback Visualization Notebook

### PR DESCRIPTION
**Pull request by sspradling78**
## Description

This is a notebook that shows some visualizations for Mentor feedback by Mentees. 

Fixes # BL-136, BL-393

## Type of change
Notebook addition

Please delete options that are not relevant.

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

Loom
https://www.loom.com/share/25bd4421e8d344658b9c2a19b6445f5f

### CODE REVIEW

**Comment by miguelaledesma** [comment]
Great work on the visualization you made it really easy to understand and follow along in the video.

**Review by rogerfvieira — COMMENTED** [review]
Being able to select the dates for which one would want to look at the feedback via the interactive visualization was a pretty cool thing.

**Review by ErinNC — APPROVED** [review]
Awesome job with the interactive visualizations. It helped me to learn a few things by commenting out lines in Colab. Also, good call on leaving the rolling mean off of the final graph. The bar graph alone conveys all the info an admin would be interested in.

The only tiny improvement I could find would be the legend title, which still has the column header 'mentor_full_name.' You guys did a great job!

**Comment by jsgersing** [comment]
This flexible visualization tool provides admins with the ability to get a quick overview, a detailed look at individual mentors' feedback outcome and vader score, and even look at sentiment changes over certain time ranges. Nice addition!

**Review by jsgersing — DISMISSED** [review]
This flexible visualization tool provides admins with the ability to get a quick overview, a detailed look at an individual mentor's feedback outcome and vader score, and even a view at sentiment changes over adjustable time ranges. Nice addition!

**Comment by sspradling78** [comment]
@ErinNC, I figured out those changes and did some more fine detail work. It looks better than before. Thanks for your input.

**Review by opeterschmidt — APPROVED** [review]
Nice work on these visualizations! The interactivity allows you to access quite a lot of information about mentor performance in overview and in detail, in a digestible manner.

**Review by marthabg — APPROVED** [review]
Good call on combining that first and last name for better clarity. I think you guys set a good range for evaluating positive vs negative vs neutral sentiments with a 0.3 threshold. I'm not sure if I did something wrong when running your notebook though because I get an error when I tried running the lines where you are adding the columns "feedback_outcome" and then "vader_score", it says "float object is not iterable". This might just be a problem on my end though, just double check if that works on your notebook, if it does, you are good to go! Very helpful graphs full of all the vital information needed from analyzing chunks of text.

**Review by sujatasahoo — COMMENTED** [review]
The visualization is very informative. Nicely done selecting the dates to see the mentor feedback.

**Pull request merged**
