### PR TITLE
Added Sentiment Analysis Endpoint to API

### PR DESCRIPTION
**Pull request by mgrohnke**
The pull-request was co-authored by Mitch Hollberg

## Description

The team added an endpoint to the DS API for future sentiment analysis usage.  Right now, this endpoint will take any input text, call vaderSentiment's SentimentIntensityAnalyzer, and will return 'positive' if the sentiment analysis compound score is greater than 1 and will return 'negative' otherwise.  Eventually this will be helpful when linked to meeting notes and will be able return a negative or positive prediction of the how the meeting went. 

vaderSentiment was added to the requirements.txt file.

API version was updated.

## Type of change

Please delete options that are not relevant.

- [ x] New feature
- [ x] This change requires a documentation update

## Checklist:

- [x ] My code follows PEP8 style guide
- [ x] I have removed unnecessary print statements from my code
- [ x] I have made corresponding changes to the documentation if necessary
- [ x] My changes generate no errors
- [ x] No commented-out code
- [ x] Size of pull request kept to a minimum
- [ x] Pull request description clearly describes changes made & motivations for said changes

https://www.loom.com/share/d269ef774b414893b926e00ca5eb962c

### CODE REVIEW

**Review by AustinJamesWolff — APPROVED** [review]
This is good. Thank you for adding this into the app, it should be useful for teams moving forward.

**Review by NPAPENBURG — APPROVED** [review]
Looks good! Straight forward endpoint!

**Review by jonathan-mcgraw — APPROVED** [review]
Simple and straightforward functionality. I love it.

**Comment by Zack-Quintana** [comment]
Good thinking about creating this feature. I can't think of any changes or improvements that can be made from it. well done!

**Review by Zack-Quintana — APPROVED** [review]
Good thinking about creating this feature. I can't think of any changes or improvements that can be made from it. well done!

**Review by yefim-g — APPROVED** [review]
Awesome addition! The Loom video was great and demonstrated the changes well!

**Pull request merged**
