### PR TITLE
adds notebook directory and example notebook

### PR DESCRIPTION
**Pull request by BrokenShell**
Adds notebook directory and example notebook

### CODE REVIEW

**Review by jinjahninjah — APPROVED** [review]
Nice example! I'm intrigued by the nearest neighbor as the features become more complex. Great Job!

**Review by xianshiw — COMMENTED** [review]
You are awesome

**Review by sysgear — APPROVED** [review]
awesome

**Review by xianshiw — APPROVED** [review]

**Review by mattclibanoff — COMMENTED** [review]
Awesome example on how to simply connect mentors and mentees to one another.

**Comment by dankositzke** [comment]
Awesome - clean, neat, and simple.

**Pull request merged**
