### PR TITLE
Altair Notebook

### PR DESCRIPTION
**Pull request by BakerJr1904**
## Description

Using Altair, this exploratory notebook will explore increasingly granular levels of visualization, utilizing Altair for its high customizability and functionality, as well as interactivity that's retained when embedded to a website. This exercise focuses specifically on mentor/mentee data in regards to high level categorical metrics, but the concepts applied can be utilized in many other areas of data visualization, including attendance time series graphs, financial/resource management (tracking usage, supply/demand growths, etc.), mentor availability for mentees by day and time, staff metric overviews like what we're about to dive into...the list goes on.

## Dependencies that are required for this change.
requests, altair, random, datetime

## Contributors
- Ryland Gomez
- John Baker

## Loom Video
https://www.loom.com/share/dffa8c4dc1fc4189af87f39a967056c2

## Trello card
https://trello.com/c/c8u60ZK9/269-as-an-admin-i-want-to-have-visualization-of-the-experience-level-on-all-mentors-to-get-a-better-understanding-of-how-to-match-me

## This is a new feature:
- [x] New feature
- [x] This change requires a documentation update

## Checklist:
- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by hollberg — APPROVED** [review]
Notebook (and graphs) look good! The interactivity of the charts, allowing drill down by category, is very useful.

**Review by yefim-g — APPROVED** [review]
The notebook looks great! This will definitely be useful for anyone in the future who wants to come back and build from it!

**Review by mgrohnke — APPROVED** [review]
This is great work - should be very helpful to future teams and for the project overall!

**Review by jinjahninjah — CHANGES_REQUESTED** [review]
Awesome research everyone! I really like the exploration, yes, some of it may be a little much for a user, but this is research, so we can explore the boundaries more. 

The only thing I would change is there is a header in your PR that's just raw markdown, but looks great otherwise 👍

**Comment by wscottreynders** [comment]
Great job John and Ryland. This will be a very versatile tool. I'm glad we will be able to apply it to different admin aspects of the website. Great job!

**Review by jrosado184 — APPROVED** [review]
Looks great! I like how every is coming together to include visualization

**Review by wscottreynders — APPROVED** [review]
I love the versatility of this notebook. I'm excited to see future implementation in tool development.

**Review by jinjahninjah — APPROVED** [review]

**Pull request merged**
