### PR TITLE
New Feature to add option to have a numerical value return from sentiment analysis. 

### PR DESCRIPTION
**Pull request by ad-victoriam-101**
same branch as Feature/numeric_sentiment_analysis

## Description

Added changes to allow for API endpoint to return a numerical value or not for sentiment function call. 

Feature addition [video](https://www.loom.com/share/ee5a4d671f8d4a36ae1128bb74f999db)

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix
- [x] New feature
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by jonathan-mcgraw — APPROVED** [review]
Beautiful, sir. Looks good!

**Review by ZacharyRock — APPROVED** [review]
Nice feature, but the title has nothing to do with what the pull request is actually achieving.  Please be more careful about this in the future.

**Comment by ad-victoriam-101** [comment]
> Thanks! I was trying to fix a github mistake when i made the branch and I thought it would take the information from the old branch. It does not, lol a good learning moment for github.

**Comment by ad-victoriam-101** [comment]
> Cool, always love more options. Not sure if you wanted one, but maybe just include a video?

Video has been added! sorry I have been having some web cam issues that i'm sorting though. 
[Video Explanation. ](https://www.loom.com/share/ee5a4d671f8d4a36ae1128bb74f999db)

**Pull request merged**
