### PR TITLE
Adds run script

### PR DESCRIPTION
**Pull request by jinjahninjah**
## Description

Created a run script using uvicorn, which should make it easier to run the API on your local port. 

### Co-Authors:

Arthur Yang
Cole Richards
Dan Kositzke
Kateryna Pasechnyk
Kevin Lynner
Matt Clibanoff
Nigel Clinton
Viet Huynh
Xianshi Wei

## Type of change

- [x] New feature
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### Loom Video:

https://www.loom.com/share/59cfbe747c8346ccb0b72a8791c6f8d8

### CODE REVIEW

**Review by sysgear — APPROVED** [review]
good idea about reload

**Review by Cole-Richards — APPROVED** [review]
Simple and Sweet little piece of code, thanks for pushing! 
Not sure if I can approve (but I do) since I'm a listed co-author.
I'll request Robert's review and see what he has to say.

**Review by Katerynapass — COMMENTED** [review]
That is simply great!

**Comment by dankositzke** [comment]
Concise and simple. Nice

**Pull request merged**
