### PR TITLE
Generated Mock Data

### PR DESCRIPTION
**Pull request by archana062031**
## Description

- As a data scientist, I want to have mock review data, so that I can perform sentiment analysis.
- Created a Dataframe with 1 million rows and 3 columns Tech_stack, Age and Gender randomly using Fortuna library.

## Fixes 

- Updated description
- Added Trello User story
- Added some markdowns explaining the notebook

## Checklist

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by ulloa** [comment]
Hi Archana, you should update the pull request with a description, per the guidelines. Also attach a Trello User story to the description.

And there must be some markdown explaining the flow of the notebook. Especially the complex parts like why you chose a poisson and what the weightedchoice objects are doing.

**Review by ulloa — CHANGES_REQUESTED** [review]
Hi Archana, you should update the pull request with a description, per the guidelines. Also attach a Trello User story to the description.

And there must be some markdown explaining the flow of the notebook. Especially the complex parts like why you chose a poisson and what the weightedchoice objects are doing.

Also please make sure .DS_Store is not included in the pull request. We can add it to .gitignore file, with the following:
```
.DS_Store
**/.DS_Store
```
You will also need to need to remove it locally or remove it from the git cache. `git rm --cached .DS_Store`

**Review by Annapurnaj91 — APPROVED** [review]
Follows Pep 8 rules and looks good

**Review by ulloa — APPROVED** [review]
DS_Store is now gone. Thank you. I also see more comments inside the notebook that clarify why you took the steps you did.

**Review by sirivennelavempati — APPROVED** [review]
Looks good to me

**Review by ChristineWangcy — APPROVED** [review]
Everything looks good to me. I suggest you add a CSV file generated if there is any or a short video showing the DataFrame created.

**Pull request merged**
