### PR TITLE
BL-588 Feature/schema cleanup update

### PR DESCRIPTION
**Pull request by woodbenwood**
## Description

- Removed MentorIntake and Resource from schema.py
- Removed updated_at field in Mentor, Mentee, MentorUpdate, and MenteeUpdate
- Changed 'heard_about' in Mentee and MenteeUpdate to 'referred_by' to match Mentor collection. 

## Type of change

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by woodbenwood** [comment]
Loom'd

**Comment by woodbenwood** [comment]
for Lo! a loom was loomed
https://www.loom.com/share/238fb935763247a8a7e6d183c475178f

**Review by sujatasahoo — APPROVED** [review]
Good update of schema.py, Mentee, and MentorUpdate. Now, Mentee and MenteeUpdate match with the Mentor collection.

**Comment by jack-semder** [comment]
Always love to see simplification of the schema! Changing to "referred by" sounds and looks much better. Nice!

**Review by kristinacernekova — DISMISSED** [review]
Nice clean up.

**Review by CrisIV — APPROVED** [review]
Great job cleaning up the schema by removing unnecessary fields. The change of heard_about to referred_by sounds much better.

**Review by miguelaledesma — APPROVED** [review]
I think is great. The more of the same fields that can be used in the mentee and mentor the better if its referring to the same topic. In this case having heard about and referred by was basically the same thing. On the BE ticket i worked on I reflected these changes so once this is merged, we are all on the same page. GREAT WORK!!

**Review by L0lbrich — DISMISSED** [review]
Good clean up!

**Review by L0lbrich — APPROVED** [review]
Good clean up, easy win!

**Review by BrokenShell — DISMISSED** [review]

**Pull request merged**
