### PR TITLE
Updated Meeting Class to match backend schema

### PR DESCRIPTION
**Pull request by yefim-g**
## Description

This was an update to the Meeting Class to further conform to the backend schema and promote easier readability.

## Type of change

Please delete options that are not relevant.

- [x] New feature (update/small tweak)

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

Loom video: https://www.loom.com/share/033654af03f541fa839d24144175c1cf

### CODE REVIEW

**Review by NPAPENBURG — APPROVED** [review]
Great updates to the work man! We are now aligned with the backend.

**Review by robstetson — APPROVED** [review]
Great work Yefim! Getting things on the same page with the backend, clean and readable code, as well as great documentation. Keep it up my friend!

**Review by jonathan-mcgraw — APPROVED** [review]
Good job sir. Looks fantastic. Thank you for clearing this up.

**Review by WaylayOvercast — APPROVED** [review]
Yefim showed a good ability to communicate during this task, Looks like his adjustments to the DS API will handle the changes to our Node DB (PR for changes to the Node db should be up shortly)

**Review by AustinJamesWolff — APPROVED** [review]
Excellent, this will help streamline data into the backend. Thank you!

**Pull request merged**
