### PR TITLE
BL-940-ds-refactoring-paying-off-some-tech-debt

### PR DESCRIPTION
**Pull request by woodbenwood**
## Description
We paid off our tech debt!
- There were some functions in data_options.py -- moved those to generators.py
- Abstracted away repetition in schema.py with Inheritance from ExtraForbid class 
- Got rid of the import * in generator file, added the appropriate individual imports

## Jira Ticket
[Jira Ticket](https://bloomtechlabs.atlassian.net/browse/BL-940?atlOrigin=eyJpIjoiNDg5M2I4ZWVjYTVjNDkxNWFjMGUzODRhYmIyMTM3MTMiLCJwIjoiaiJ9)

## Type of Change
- [x] Bug fix
- [x] New feature

## Checklist
- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by jinjahninjah — APPROVED** [review]
Nice job on keeping the codebase DRY and adding to the intuitiveness of where the functions are housed 👍

**Review by zoebrantley — APPROVED** [review]
After these changes, the code looks much cleaner! The ExtraForbid class was a great way to free up some extra space.

**Review by Austin-T-Johnson — APPROVED** [review]
Great job cleaning up the code and moving the functions to a more appropriate file. Your code is very clean and easy to read, making it understandable even for someone from the web side!

**Review by Nicholas-R-Payne — APPROVED** [review]
Good job cleaning up the code!

**Pull request merged**
