### PR TITLE
Update utilities.py

### PR DESCRIPTION
**Pull request by jonathan-mcgraw**
## Description

Fixed the financial_aid_gen() to be able to work with the updated database.
Changed variable names to decrease namespace.
Created a sub-function for easy future-proofing, and decrease return statement.
Changed return output to show a percentage rather than a decimal.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix
- [ ] New feature
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

https://www.loom.com/share/f8b08f5121ca45c3a0c1e66d7704fb91

### CODE REVIEW

**Review by AustinJamesWolff — APPROVED** [review]
Awesome, this should help streamline things on the backend.

**Review by AustinJamesWolff — APPROVED** [review]
Awesome, this should help streamline things on the backend.

**Review by mgrohnke — APPROVED** [review]
Great fixes, looks good!

**Comment by Zack-Quintana** [comment]
These fixes look good. Don't see any corrections that need to be made

**Review by Zack-Quintana — APPROVED** [review]
These fixes look good. Don't see any corrections that need to be made

**Pull request merged**
