### PR TITLE
Updates random generators, deletes unused code

### PR DESCRIPTION
**Pull request by BrokenShell**
Updates random generators, deletes unused code.

- [x] Bug Fix

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by MichaelJP-DS — APPROVED** [review]
Nice job cleaning up the codebase Robert!  Looks good.

**Review by ZacharyRock — APPROVED** [review]
Nice to see uuid implementation.

**Review by AustinJamesWolff — APPROVED** [review]
Great work. It works, and looks good to me.

**Review by yefim-g — APPROVED** [review]
Everything looks good! Nice edits.

**Pull request merged**
