### PR TITLE
Added Visualization

### PR DESCRIPTION
**Pull request by Zack-Quintana**
Added 3 more graphs to further increase readability and effectiveness.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by hollberg — APPROVED** [review]
Great work adding additional chart options. Given the sparse and relatively homogenous nature of the test data, the current visualizations look sort of plain, but the structure of the code and the chart types will prove to be very informative once we push real data through this pipeline. Kudos for building out tooling and visualizations whose value will only be fully realized by future cohorts.
"Blessed Are Those Who Plant Trees Under Whose Shade They Will Never Sit" ;)

**Review by BrandonSmith710 — APPROVED** [review]
Nice job, the visualizations were clear and easy to learn from.

**Review by mgrohnke — APPROVED** [review]
These visualizations look great! Nice work.

**Review by jinjahninjah — CHANGES_REQUESTED** [review]
Nice work! The only thing I would say is to give Altair a try. 

You also need a Loom video and you should be set 👍

**Review by arsalan2243 — APPROVED** [review]
these added visualizations can help us to understand it better and increase efficiency. good job.

**Review by OlatomiAdigun — APPROVED** [review]
Good job with the visualization

**Review by jinjahninjah — APPROVED** [review]

**Pull request merged**
