### PR TITLE
Feature/job description scraper austin

### PR DESCRIPTION
**Pull request by AustinJamesWolff**
## Description

We created a notebook that scrapes LinkedIn.com's job openings page to save job titles, company names, locations of jobs, and job descriptions into a .csv file. We needed to get this data in order for future teams to build an NLP model that matches a mentee's resume with related job descriptions from job openings.

Loom: https://www.loom.com/share/e2b44bf47b6040e49c25c63d4b1afb8b

Co-authored-by: Scott wscottreynders@gmail.com

## Type of change

- [ X] New feature

## Checklist:

- [x] My code follows PEP8 style guide (USED JUPYTER NOTEBOOK ONLY)
- [x ] I have removed unnecessary print statements from my code
- [x ] I have made corresponding changes to the documentation if necessary
- [ x] My changes generate no errors
- [x ] No commented-out code
- [ x] Size of pull request kept to a minimum
- [x ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by BakerJr1904 — APPROVED** [review]
I can't wait till we link this feature with mine.

**Review by NPAPENBURG — APPROVED** [review]
This is a really good start to something that can be big. Looking forward to seeing how this plays out in the future!

**Comment by Zack-Quintana** [comment]
Wow! This is really going to help in the future. There's nothing that I can see to change or fix. The only addition that I can think of would be to try to include indeed.com results or other job listing sites, but that's all extra stuff. This looks really good. Nice.

**Review by yefim-g — APPROVED** [review]
Definitely a cool feature, there's lots of potential that can follow!

**Comment by adamhinton** [comment]
Very nicely done, and I can't find any issues with it!

**Pull request merged**
