### PR TITLE
Update Johns_Application_scanner.ipynb

### PR DESCRIPTION
**Pull request by BakerJr1904**
## Description

Using NLTK, this add-on changes the way data can be entered into the application scanner, and introduces the data cleaning function. Because we listen to reviews form colleges, we are changing how resumes and job descriptions are inputted. You don’t need to upload a docx file anymore. Now front-end can use a text-area to take in the data that is pasted into the text-area and just save it in a variable. The data that is entered is passed into the cleaning function to be cleaned and processed.  

The Cleaning Function: 
- Takes in a variable with a multiline string inside
- Removes all numbers 
- Changes all uppercase to lowercase
- Strips the spaces, tabs, and newlines from the front and back
- Takes out email addresses
- Takes out all punctuation
- Separates the words
- Deletes stop words
- Uses lemmatization to get the root word

Yes, this removes ‘python3’ to ‘python’ but it is better than comparing zip-codes, phone numbers, and addresses. Things that can never be the same in the resume and job description. This like any code is not perfect, and we open to any ideas to make it better.
We did keep this promise “soon docx will not be needed because of future pull requests”.

## Dependencies that are required for this change.
re, string, nltk

## Video
https://www.loom.com/share/4c370ed5d6d844aeb3ebb9404af7381c?sharedAppSource=personal_library

## Contributors
- John Baker
- Javier Rosado

## Trello
https://trello.com/c/7ATIWVxU/261-as-an-administrator-i-want-to-have-a-computer-program-that-can-review-an-application-and-compare-it-to-a-sample-job-description

##This is an add-on to the application scanner feature.

- [x] Add-on feature
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by hollberg — APPROVED** [review]
Interesting investigation into using cosine similarity as a way to find similar job postings. As this is further operationalized, this can be used to surface only the most relevant job postings to mentees, which will save them time and frustration in the job search process.

**Review by DagimB — APPROVED** [review]
Really nice that you do not need Docx files anymore, and fantastic job on the cleaning function and cannot wait until it is hooked up to the application scraper later on. It would be interesting to see how stemming differed from lemmatization in this case.

**Review by BrokenShell — CHANGES_REQUESTED** [review]
Lets get rid of those pipenv config files!
- `Pipfile`
- `Pipfile.lock`

**Review by BrokenShell — APPROVED** [review]

**Review by Zack-Quintana — APPROVED** [review]
There aren't any changes that I can see needing to be made.

**Pull request merged**
