### PR TITLE
updates requirements.txt for Apple Silicon compatibility

### PR DESCRIPTION
**Pull request by BrokenShell**
## Description

Updates `requirements.txt` for Apple Silicon compatibility. Locks external libraries to known working versions of all dependencies. Please make sure to run `pip install -r requirements.txt --upgrade` after pulling this change.

### CODE REVIEW

**Comment by BrokenShell** [comment]
> Error when I run `pip install -r requirements.txt --upgrade` : I recall having uvloop issues in the past. Maybe it's a Windows thing? image

Can you try removing the line with uvloop and run it again? Thanks for testing this!!!

**Comment by sayerjk** [comment]
All good now with uvloop removed from `requirements.txt`. No errors installing or with `responses_analysis` endpoint

image

**Review by sayerjk — DISMISSED** [review]
Nice changes we have now tested on Windows and Mac thanks to a little road bump I had getting mine running on Windows 10 (see comments on this PR). Everything running smoothly for me and hopefully this edit will eliminate some future troubleshooting.

**Review by sspradling78 — APPROVED** [review]
Good update

**Pull request merged**
