### PR TITLE
Feature/job scraper package austin

### PR DESCRIPTION
**Pull request by AustinJamesWolff**
## Description

There needs to be a package that future Underdog Team Members can use to easily scrape LinkedIn for job openings, for multiple purposes, such as gathering current job openings, but perhaps more importantly, use NLP to match mentee's resumes to job openings by similarity. I had already built a notebook that gathered job opening data from LinkedIn for purposes of the Data Science team to build the first NLP model, there will be a need for more data. So I have adapted the code into an importable package for anyone to use in any script or notebook (and for Admin's or those on the Data Science team to have more flexibility in how LinkedIn is scraped).

Loom: https://www.loom.com/share/b426a4d3c39244faaf14ab6687bb67a2

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by hollberg — APPROVED** [review]
This looks great. I couldn't get it fully working on windows due to directory path issues, but it launched selenium and scraped data from my LinkedIn account just great.

This will be a lifesaver for future DS team members to quickly collect job description corpuses for training models and for matching to students.

**Comment by Zack-Quintana** [comment]
Looks and works great. Excellent work! This will help incredibly in the future.

**Review by NPAPENBURG — APPROVED** [review]
This is a great start to a new feature. I am curious to how this would be integrated with the app since we would need the linked login and password of a user and a place to display or save the CSV file for each user. Otherwise like I said this a great start! Good stuff!

**Review by DagimB — APPROVED** [review]
Wonderful job with this package. The detailed comments about how the code works is really useful for the future as well!

**Review by BrokenShell — CHANGES_REQUESTED** [review]
Good job over all but, lets get rid of the vscode config files.

**Review by BakerJr1904 — APPROVED** [review]
This will help the mentees job search. Nice use of NLP

**Comment by AustinJamesWolff** [comment]
> Good job over all but, lets get rid of the vscode config files.

Done!

**Review by BrokenShell — APPROVED** [review]

**Review by Zack-Quintana — APPROVED** [review]
Looks and works great. Excellent work! This will help incredibly in the future.

**Pull request merged**
