### PR TITLE
NLTK Application Scanner

### PR DESCRIPTION
**Pull request by BakerJr1904**
## Description

Using NLP with 
- NLTK
- Count Vectorizer
- Fit Transform
- Cosine Similarity

And the Custom Cleaning Function: 
- Takes in a variable with a multiline string inside
- Removes all numbers 
- Changes all uppercase to lowercase
- Strips the spaces, tabs, and newlines from the front and back
- Takes out email addresses
- Takes out all punctuation
- Separates the words
- Deletes stop words
- Uses lemmatization to get the root word

This feature takes a job description and compares it to a resume. It returns a percentage of how much your resume matches the job description. 

We compared: 
- Two data science resumes to a bakery job
- Two data science resumes to a data science job
- The bakery job to the bakery job
- The data science job to the data science job

The results of the bakery job description compared to the data science resume were dramatically lower with the cleaning function. We got a very low score of 4% compared to the 54% without the cleaner. There was a dramatic drop in actual score with the data science job description compared to the data science resume also, 35%. But the gap between the bakery job description compared to the data science resume, and the data science job description compared to the data science resume grew from 15% to 30%. 
## The gap is the most important data, and it doubled with the new cleaning function. 
When your score is 25% or more this could be a good indicator that you should apply for the job.

## Loom Video
https://www.loom.com/share/fb6ca37c18364cc7ab46691494f2d08f

## Trello card
https://trello.com/c/7ATIWVxU/261-as-an-administrator-i-want-to-have-a-computer-program-that-can-review-an-application-and-compare-it-to-a-sample-job-description

## This is a combination of two features.

- [x] Combination of two features
- [x] This change requires a documentation update

Dependencies that are required for this change.
Nothing that wasn’t in the other two pull requests.

## Contributors
- John Baker
- Scott Reynders

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by jrosado184 — APPROVED** [review]
wow, huge difference in percentages but way more accurate, this gives anyones using it more confidence if there is match. Good job guys!

**Review by DagimB — APPROVED** [review]
Wonderful job on getting the application scanner to work more accurately. Testing it with the bakery job you mentioned gets us a better picture of how it works as well. Overall, I'm glad that the model trends correctly

**Review by jinjahninjah — APPROVED** [review]
Great Job! This looks like it will be helpful to source some jobs for the mentees. Excited to see how this is implemented in the project 👍 

:shipit:

**Review by hollberg — APPROVED** [review]
Great improvement in the metrics. Crossing this threshold will save mentees lots of time and effort and allow them to really focus on applying for the most relevant jobs. Great application of data science!

**Review by SheebaHashmi — APPROVED** [review]
Excellent work! This data visualization would be really helpful once we embed this in our frontend.

**Review by maidiance — APPROVED** [review]
This code looks like magic to me, but the result looks like amazing and helpful metrics that would be very useful to employ.

**Review by BrandonSmith710 — APPROVED** [review]
This looks great, a well-deserved edge for the mentees that I think will quicken the job hunt and also lead to more fruitful employment.

**Pull request merged**
