### PR TITLE
Sprint 4

### PR DESCRIPTION
**Pull request by BrokenShell**
## Description
Adds MongoDB Interface and API. Also prepares repo for AWS EB deployment.

Added Files:
/.elasticbeanstalk
.ebignore

## Contributors
Robert Sharp
Kevin Lynner
Arthur Yang
Cole Richards
Kateryna Pasechnyk
Nigel Clinton
Royce Roberts
Viet Huynh

## Type
- [x] New features

## Checklist:
- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by jinjahninjah — APPROVED** [review]
Looks awesome! Rather large PR, but it still leaves room for more as that matcher class is empty. I'm excited to get the model up and running as well :)

**Review by Cole-Richards — APPROVED** [review]
Fun to be a part of creating this pull request. 

The spelling out of Project, cluster, databases, and collections is helpful.

The code looks clean. 
Looking forward, likewise, to uploading a model interface.

**Review by nhockcuncon77 — APPROVED** [review]
This is awesome, I learn a lot about how to add MongoDB Interface, API, and AWS.

**Review by Katerynapass — COMMENTED** [review]
It's amazing!

**Comment by LynnerKevin** [comment]
Good to have it available for us to start working on it and expanding it ourselves

**Comment by mattclibanoff** [comment]
Enjoyed learning this in lecture. I'd love to use this as a springboard for my own work later!

**Comment by dankositzke** [comment]
Cool and interesting to see how the API is built how we can utilize AWS for the project.

**Pull request merged**
