### PR TITLE
BL-903 DS API Organization into Routers

### PR DESCRIPTION
**Pull request by stevenhastings**
## Description
Reorganized data operations for existing API into separate routers using FastAPI's APIRouter tool.  This new addition will give more clarity for the developer when viewing the Swagger documentation and also make things more digestible for new learners entering labs. There is still more to be done and I am open to thoughts about further organization tactics.  So, this first pull request is just to make sure we're on the right path with what we have so far. 

If you'd like to learn more about FastAPI Routers, Robert delivered a great workshop covering it, I'll leave the link below. 

- [Link to DS_Workshop_API_Routers_and_Swagger ](https://hub.bloomtech.com/s/article/Labs-Recordings)

## Type of Change
- [x] New feature
- [x] This change requires a documentation update

## Checklist
- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

## [Loom Video](https://www.loom.com/share/6dedcb93121a405da9bee95082f4abf0)

### CODE REVIEW

**Review by Charles-Merrill-Johnson — APPROVED** [review]
I think going with fastAPI was a great call for the DS team. It really is one of the best frameworks for Python. Robert and the DS team are killing it! great job

**Review by jtorres03 — DISMISSED** [review]
Sweet! Everything looks good and much more organized! Thanks Steven!

**Review by jack-semder — APPROVED** [review]
I remember seeing this in the workshop! Great job Steven, awesome changes!

**Review by jtorres03 — DISMISSED** [review]
Ah! Glad we got the few issues fixed! Removed the prefix and added router.db. Sweet! GOOD JOB

**Review by BrokenShell — DISMISSED** [review]
I had to resolve a huge merge conflict due to the fact that multiple PRs edited the same code recently, but all looks good now!

**Review by BrokenShell — APPROVED** [review]
One more little merge conflict fix. I'm not sure how some of the recent changes got rolled back, but all is well now! Great job refactoring the API.

**Review by jtorres03 — APPROVED** [review]
Perfect! Hopefully no more changes need to be made!

**Pull request merged**
