### PR TITLE
VietHuynh

### PR DESCRIPTION
**Pull request by nhockcuncon77**
It is the simple model that matches the mentee with the mentor.
@Katerynapass @sysgear 
https://www.loom.com/share/87ffea52936c45b1a3f7726bd0017e71

### CODE REVIEW

**Review by dankositzke — CHANGES_REQUESTED** [review]
Awesome the algorithm works well. The only thing I would change is:

- code cell 2 line 4:  data --> data1

**Review by jinjahninjah — APPROVED** [review]
The model looks great! I see the fix for Dan's comment was implemented, nice! I'm intrigued to see what happens when we get more complex data. Looks good though! 👍  

Also, don't forget to use the PR template for your description section. Once you have that and the video, this should be good to go 😄

**Review by sysgear — APPROVED** [review]
yes, great experiment for match and also suggested changes made

**Review by Cole-Richards — CHANGES_REQUESTED** [review]
I'd like to see the video explaining what is going on here. 
I think Royce said it best, get the template that we are supposed to follow as a way of pre-screening out pull requests and then the ~2 min video explaining what you did/changed. 
*I'll see about finding it and sending it your way

Simple model, I'd like to see more complexity.

**Comment by Cole-Richards** [comment]
Template is here: https://github.com/BloomTech-Labs/underdog-devs-ds-a/blob/main/pull_request_template.md

**Review by dankositzke — APPROVED** [review]
Great!

**Comment by NigelClinton** [comment]
Echoing Cole & Dan's changes.

**Comment by mattclibanoff** [comment]
The models you guys built are super cool, but there are a lot of notebooks. Would love a quick Loom video running through them all!

**Review by Cole-Richards — APPROVED** [review]
I'd like to see the video explaining what is going + the template for pull requests but I really like your work. MVP all the way. Template is here: https://github.com/BloomTech-Labs/underdog-devs-ds-a/blob/main/pull_request_template.md

**Pull request merged**
