### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Cole-Richards**
## Description
Richards/Pasechnyk/Huynh contributions

Mock data using the Fortuna toolkit. 

Added soft skills to dictionary, statistically relevant tech stacks, related convictions to type of crime, need for financial assistance, and other potential matching features. 

https://www.loom.com/share/fc68f06b3426422b8f9225e3e9fe9cac
Recommend watching on double speed ;)

## Type of change

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by BrokenShell — APPROVED** [review]
This looks fantastic.

**Review by RylandGomez — APPROVED** [review]
The added features are definitely important for a variety of reasons. Well explained, I definitely think this should be included in main for reference and further exploration.

**Review by Annapurnaj91 — APPROVED** [review]
Everything looks good

**Review by archana062031 — APPROVED** [review]
Looks good!

**Pull request merged**
