### PR TITLE
Added notebook that forecasts mentee desired skills

### PR DESCRIPTION
**Pull request by dankositzke**
## Description

Appending time series forecasting for mentee desired skills onto a previous mock data generation notebook. This could allow admin to anticipate the quantity of incoming mentees that are trying to learn a specific skill, and it could guide admin's decisions about what skills they need to seek out in the mentors they try to attract. 

01/29/22 Edits per Ryan Hamblin's feedback:
- Adjusted code format to PEP8
- Created new dataframe for forecasting (mentee_df_forecasting) to avoid 'copy of a slice' warning
- Implemented max(0,prediction) function to change any negative values to 0

## Type of change

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

https://www.loom.com/share/a6a8761f3b694568b5b6a9e0c76d76ac

### CODE REVIEW

**Comment by ryan-hamblin** [comment]
The first thing to note is that there are a few discrepancies in formatting. You have a few instances where tabs are being used over spaces or 2 spaces vs 4 spaces. Pep8 will bark at this when the code is transitioned into the repository. 

As per @BrokenShell we'd love to ensure that we're following pep8 even in our notebook development flow. This will save you lots of time in the long run. 

Another thing we noted was: 

```/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1596: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead```

It seems you have a warning in the Forecasting section of the notebook. 

Try using `.loc` in lieu of `.at` same syntax but this was found in a couple of different sections throughout the notebook and it can/should be easily cleaned up. 

Also in your forecast, we saw that there was a `negative` output for the SQL skill. Let's look into this as it seems like it might be a problem but it could also be a side-effect of the library/package you're using. 

Overall great work here and super valuable for the product and its features moving forward.

**Review by sysgear — APPROVED** [review]
I like the idea of appending time series forecasting; also read the comments from Ryan for my learning as well.

**Review by mattclibanoff — APPROVED** [review]
I think using Euclidean Distance to solve this problem is super interesting, but I wonder if you're not complicating things a bit. I feel like Cosine Similarity may be a bit easier. That said great work! This is definitely very cool stuff.

**Comment by NigelClinton** [comment]
Looks great! I love the time series forecasting. I think that's an interesting approach.

**Comment by nhockcuncon77** [comment]
I like the way you approach this problem too. That is so cool.

**Pull request merged**
