### PR TITLE
Adds cosine similarity Model to Royce Roberts' Mock Dataset.

### PR DESCRIPTION
**Pull request by mattclibanoff**
## Description

Adds Cosine Similarity model to Royce Roberts' Mock Dataset. This model ranks the mentors in order of relevancy to the mentees' skills/availability.  

### Coauthors 
Royce Roberts
Xianshi Wei 
Cole Richards

### Video
https://www.loom.com/share/9cc5f69cae5c4266a5e52ca4082c4f45

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by NigelClinton** [comment]
Looks great! The only small thing I'd say is there's a few blank cells at the bottom of the notebook.

**Review by sysgear — APPROVED** [review]
Cosine similarity is a good idea and also mentioned in our DS office hour.

**Review by dankositzke — APPROVED** [review]
Nice work! Based on what Jason said in yesterday's meeting, the cosine similarity number could be a good representation for a 'Percentage Match' for admin to view when they make the final matching decision. Also it sounds like they will test the 'Number of Stars' representation and see which is better for the admin.

**Review by nhockcuncon77 — APPROVED** [review]
This is a very good approach and impressive work.

**Pull request merged**
