### PR TITLE
Uncommented code that was left commented on accident.

### PR DESCRIPTION
**Pull request by NPAPENBURG**
## Description

There was some important code that commented out by myself. I went back in and uncommented it.
Loom: https://www.loom.com/share/18f6ec200f9c45a7925a5d38d4b11c76
## Type of change

Please delete options that are not relevant.

- [x] Bug fix

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by yefim-g — APPROVED** [review]
Easy fix, nice catch!

**Review by jinjahninjah — APPROVED** [review]
Nice catch!

**Comment by jonathan-mcgraw** [comment]
Good catch, sir!

**Review by jonathan-mcgraw — APPROVED** [review]

**Review by jinjahninjah — CHANGES_REQUESTED** [review]
This needs a quick Loom video going over why this code needs to be un-commented, but nice catch!

**Comment by NPAPENBURG** [comment]
> This needs a quick Loom video going over why this code needs to be un-commented, but nice catch!

I will be doing the Loom video right after this meeting.

**Review by mgrohnke — APPROVED** [review]
Nice catch, looks good!

**Review by jinjahninjah — APPROVED** [review]

**Review by adamhinton — APPROVED** [review]
These simple fixes can be the hardest to catch. Good job.

**Review by morgankj — APPROVED** [review]
Well done! Little errors like this easily slip through the cracks - great job!

**Comment by mohamedmosaed** [comment]
great catch

**Review by WaylayOvercast — COMMENTED** [review]
cant remove this comment >:)

**Review by AustinJamesWolff — APPROVED** [review]
Looks ready to me.

**Comment by Astrospence** [comment]
I really liked the simplicity and professionalism of your video explanation. Even though it was a small change, you still made it feel important and relevant.

**Pull request merged**
