### PR TITLE
Feature/topic model vectorized

### PR DESCRIPTION
**Pull request by BrandonSmith710**
Description
The following change includes a function which can accept a list of all feedback texts or meeting notes,
and return the specified number of most prevalent topics discussed.

Type of change
- [ ] Bug fix
- [x] New feature
- [x] This change requires a documentation update

Checklist:
- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

https://www.loom.com/share/b272dfd36f6e42e3ab271b67ea043d89

### CODE REVIEW

**Review by Ike888 — CHANGES_REQUESTED** [review]
Merge conflict alert! 
Numpy should be lower case and version 1.22.3
This matches the version in Pandas.

**Comment by BrandonSmith710** [comment]
> Merge conflict alert! Numpy should be lower case and version 1.22.3 This matches the version in Pandas.
Sure thing, thanks for catching that. I just resolved it.

**Review by BrokenShell — CHANGES_REQUESTED** [review]
Great start, I'd like to see a few examples documented inside the notebook. Also, how might this topicizer be used in the app?

**Comment by BrandonSmith710** [comment]
> Great start, I'd like to see a few examples documented inside the notebook. Also, how might this topicizer be used in the app?

Thanks, I'll get a couple of examples into the notebook. I was thinking for the use case, that mentees could look at the topics produced by feeding topicizer a list of every mentee's recent feedback, or a list of all mentees interested in, ex data science(maybe I could add an optional parameter for field of interest), make decisions when considering current events, and gauge where the collective of pertinent mentors is generally steering the collective of mentees.

**Comment by Ike888** [comment]
> 

Let me start by saying that you're doing fantastic -something I forgot to mention in my previous comment!
The examples will go a long way, at least for me, to understand your vision and see what else/fields could be implemented.

**Review by jinjahninjah — APPROVED** [review]

**Review by jinjahninjah — CHANGES_REQUESTED** [review]
Don't forget the Loom video

**Comment by BrandonSmith710** [comment]
> Don't forget the Loom video

Thanks

**Review by jinjahninjah — APPROVED** [review]

**Review by BrokenShell — APPROVED** [review]

**Review by BrokenShell — CHANGES_REQUESTED** [review]
We have some scikit warnings that need to be addressed. Also, can you describe (in the notebook) how you see this code being used in the app?

**Comment by BrandonSmith710** [comment]
> We have some scikit warnings that need to be addressed. Also, can you describe (in the notebook) how you see this code being used in the app?

Absolutely.

**Review by AdamHVu — APPROVED** [review]
Looks good to me!

**Review by Ike888 — APPROVED** [review]

**Review by BobbyWilt — APPROVED** [review]

**Comment by BrandonSmith710** [comment]
> Look great, a very clean implementation of code. The cleaner function is simple and straight to the point. Same with the topicizer.

Thanks!

**Comment by BrandonSmith710** [comment]
> Looks good to me!

Thank you!

**Review by BrokenShell — APPROVED** [review]

**Pull request merged**
