### PR TITLE
Feature/seeds

### PR DESCRIPTION
**Pull request by BrokenShell**
# Workshop Code

## Description
- Adds seed class for populating MongoDB with random data.
- Updates .gitignore
- Updates Resource class to support string ids

## Contributors
- John Baker
- Jonathan McGraw
- Eisenhower Lancheros
- Mitch Hollberg
- Sheeba Hashmi

## Type
- [x] New feature

## Checklist:
- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by jinjahninjah — APPROVED** [review]
The seeds.py is going to help in the pursuit of sciencing our data!

:shipit:

**Review by jonathan-mcgraw — APPROVED** [review]
This is awesome. Thank you for following up so quickly!

**Review by jinjahninjah — APPROVED** [review]
Thanks for getting rid of that checkpoints ipynb!

:shipit:

**Review by hollberg — APPROVED** [review]
Having more and better mock test data will make it much easier to develop other Data Science features.

**Pull request merged**
