### PR TITLE
Generating Mock Reviews Data

### PR DESCRIPTION
**Pull request by Annapurnaj91**
## Description

- As a data scientist, I want to have mock review data, so that I can perform sentiment analysis
- Generating Mock Reviews Data with data frame containing mentor_id, mentee_id and reviews.
https://www.loom.com/share/4617146518aa48289d8de31de42c78f7

## Fixes

- Added Loom video in the description

## Type of change

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

## Contributors
BhavaniLakshmi Annapurna Jagarlamudi
Archana Coimbatore Sivagurunathan

### CODE REVIEW

**Review by ev-horrosh — APPROVED** [review]
csv is very useful. we'll tie ids to mongo (it's a work in progress since someone mentioned it has to be generated upon uploading to db)

**Review by archana062031 — APPROVED** [review]
Everything looks good to me!

**Review by sirivennelavempati — APPROVED** [review]
Looks good to me

**Comment by ChristineWangcy** [comment]
A great resource of mock paragraph reviews created! Everything looks good to me.

**Review by ChristineWangcy — APPROVED** [review]
A great resource of mock paragraph reviews created! Everything looks good to me.

**Review by rodricobsanchez — APPROVED** [review]
looks clean, docstrings in check, great

**Review by cainpalmer — APPROVED** [review]
Code is still clean with no spaces or extra unnecessary lines. Awesome job.

**Review by paulstgermain — CHANGES_REQUESTED** [review]
This PR needs a Loom/video walkthrough of the changes made before I can merge it! 😱

**Review by paulstgermain — APPROVED** [review]

**Pull request merged**
