### PR TITLE
updates LICENSE file

### PR DESCRIPTION
**Pull request by BrokenShell**
## Description
Small change to update the LICENSE file

### CODE REVIEW

**Review by woodbenwood — APPROVED** [review]
A necessary edit, and overdue. What would be ideal would be to "make a function" that could find all such edits and apply them all at once. But i dream.

**Comment by BrokenShell** [comment]
> A necessary edit, and overdue. What would be ideal would be to "make a function" that could find all such edits and apply them all at once. But i dream.

That's not impossible. 🫠

**Review by L0lbrich — APPROVED** [review]
Easy win!

**Review by jinjahninjah — APPROVED** [review]
You have to love those copyright updates 👍

**Pull request merged**
