### PR TITLE
Remove unnecessary imports

### PR DESCRIPTION
**Pull request by nikolayglushetskiy**
## Description
Remove unnecessary imports from the helper file, because helper doesn't use these modules.

## Jira Ticket
https://bloomtechlabs.atlassian.net/browse/BL-1039

## Type of Change
- [x] Bug fix

## Checklist
- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

## Loom Video
Changes too small to make a loom video.

### CODE REVIEW

**Review by jtorres03 — APPROVED** [review]
Good to go!

**Review by jinjahninjah — CHANGES_REQUESTED** [review]
The only change I would make is to remove the boilerplate (template) code in the description and  replace with why the imports were unnecessary, I think th and put a link to the Jira ticket in the description and it's good to go 👍

**Comment by nikolayglushetskiy** [comment]
> The only change I would make is to remove the boilerplate (template) code in the description and replace with why the imports were unnecessary, put a link to the Jira ticket in the description, and it's good to go 👍

Changes accepted and implemented!

**Review by jinjahninjah — APPROVED** [review]

**Review by TophertheCoder — APPROVED** [review]
good job removing the unnecessary imports.

**Pull request merged**
