### PR TITLE
This PR is part#2 PCA, Mentor-Mentee Match, via Vectorization, PCA(Principal Component Analysis), Clustering, and Test Search for the Best Model

### PR DESCRIPTION
**Pull request by nhockcuncon77**
## Description

Mentor-Mentee Match, via Vectorization, PCA(Principal Component Analysis), Clustering, and Test Search for the Best Model
Fixes # (issue)

@sysgear @Cole-Richards @Katerynapass 
https://www.loom.com/share/55aea33f03894a62873888c5ff563274

## Type of change

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by sysgear — APPROVED** [review]
I like about scaling the data before PCA

**Review by Katerynapass — APPROVED** [review]
Great job!

**Review by Cole-Richards — COMMENTED** [review]
Blown away by your efficiency in modeling!

**Review by Cole-Richards — APPROVED** [review]
Well done!

**Pull request merged**
