### PR TITLE
Added certifi library to requirements.txt

### PR DESCRIPTION
**Pull request by nikolayglushetskiy**
## Description
Please include a detailed summary.

## Jira Ticket
https://bloomtechlabs.atlassian.net/jira/software/c/projects/BL/boards/10?modal=detail&selectedIssue=BL-1026

## Type of Change
- [x ] Bug fix
- [] New feature
- [ ] This change requires a documentation update

## Checklist
- [ X] My code follows PEP8 style guide
- [ X] I have removed unnecessary print statements from my code
- [ x] I have made corresponding changes to the documentation if necessary
- [ x] My changes generate no errors
- [ x] No commented-out code
- [ x] Size of pull request kept to a minimum
- [ x] Pull request description clearly describes changes made & motivations for said changes

## Loom Video
Changes too small to create a loom video

### CODE REVIEW

**Review by randynobx — APPROVED** [review]
Perfect. Noticed this issue a few days ago!

**Review by zoebrantley — APPROVED** [review]
Well done. Not a lot to say here other than that, haha.

**Review by woodbenwood — APPROVED** [review]
Concerned that this sets a dangerous precedent of just adding things willy-nilly, but I'm grudgingly on board.

**Review by JeffDesch — APPROVED** [review]
No problems detected, besides cleaning up the PR form's markdown a little in the future

**Pull request merged**
