### PR TITLE
Incremented api version # to 0.44.2

### PR DESCRIPTION
**Pull request by hollberg**
Co-Authored-By: Matt Grohnke <m.grohnke@gmail.com>

## Description

The Data Science api functionality was updated and merged, but the api version numbering was not updated along with the code change. 

Incremented ds api version from 0.44.1 to 0.44.2.
Also cleaned up docstring in 'financial_aid' function (removing duplicated "the" strings).

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix

## Checklist:

- [x ] My code follows PEP8 style guide
- [x ] I have removed unnecessary print statements from my code
- [x ] I have made corresponding changes to the documentation if necessary
- [x ] My changes generate no errors
- x[ ] No commented-out code
- [x ] Size of pull request kept to a minimum
- [x ] Pull request description clearly describes changes made & motivations for said changes

Pair Programming:
Who you paired with: Matt Grohnke
What pairing method(s) you used: Driver-navigator
How did it go? What did you learn?: This is my first (hopefully most minor) pull request, but Matt showed me how to leverage GitHub Desktop to simplify the pull request lifecyle. 

Loom Video:
https://www.loom.com/share/de93e5931a8e47ea82f7a00109a0724e

### CODE REVIEW

**Review by jonathan-mcgraw — APPROVED** [review]
Wow, we were talking about about this in the workshop no more than 5 minutes ago. Thank you for being so prompt, and also catching a typo in the current code. Excellent work.

**Review by NPAPENBURG — APPROVED** [review]
Great update to the version. Also good catch on the double "the" in the doc string.

**Review by AustinJamesWolff — APPROVED** [review]
Great catch. It's always good to keep the documentation up to date, as well as fix any grammar errors (those can sometimes drive developers insane).

**Review by ZacharyRock — APPROVED** [review]
Nice find on the duplicate.

**Comment by Zack-Quintana** [comment]
Nice catch on these issues. Good Job

**Review by BrokenShell — APPROVED** [review]
so fast! Good job. Not much to say about this one, let's keep that version rolling up as we make changes to the API.

**Review by jinjahninjah — APPROVED** [review]
:shipit:

**Review by Zack-Quintana — APPROVED** [review]
Nice catch on these issues. Good Job

**Pull request merged**
