### PR TITLE
Updates contribution section for DS readme.md file

### PR DESCRIPTION
**Pull request by jtorres03**
## Description

Updated DS README file to include all contributors. Motivation was to give credit to those who have contributed to this project. 

Fixes # (BL-799)

Loom Video 
https://www.loom.com/share/809ea213d12242e0890e880fb84ec8e1

## Type of change

Please delete options that are not relevant.

- [X]  Updated file

## Checklist:

- [X] My code follows PEP8 style guide
- [X] I have removed unnecessary print statements from my code
- [X] I have made corresponding changes to the documentation if necessary
- [X] My changes generate no errors
- [X] No commented-out code
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Charles-Merrill-Johnson — APPROVED** [review]
Looks much better! Nice and organized! It is always nice to be recognized as a contributor! Nice job!

**Review by nathancai97 — APPROVED** [review]
Great job updating the README, it looks a lot more organized!

**Review by stevenhastings — APPROVED** [review]
Great job! I know it is a small issue but, you got to the bottom of it and added some unexpected functionality to it.

**Review by jack-semder — APPROVED** [review]
The updated format looks fantastic, nice work!

**Review by MelodyLayne — APPROVED** [review]

**Pull request merged**
