### PR TITLE
Dankositzke2

### PR DESCRIPTION
**Pull request by dankositzke**
## Description
Expanded Royce and Matt's notebook to include an algorithm that suggests 5 mentees for each mentor.

## Type of change

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

https://www.loom.com/share/25a96cf7d9bc4d6ea9f4f3f9872f1cea?sharedAppSource=personal_library

### CODE REVIEW

**Comment by NigelClinton** [comment]
Nice work! Great thinking using Euclidean distance.

**Review by NigelClinton — APPROVED** [review]
Nice work! Great thinking using Euclidean distance.

**Review by jinjahninjah — CHANGES_REQUESTED** [review]
This looks awesome! There should be more consistency with style; such as spacing, it works for the notebook, but isn't PEP 8 compliant because it's not the 4 spaces, it's only 2. 

I really like your incorporation of time series data, once we have real data, this could be very informative for the team at Underdog Devs. 

Once the spacing is fixed, we can copy and paste straight from the notebook, otherwise, really awesome job Dan! Very insightful!

**Comment by sysgear** [comment]
Impressive work

**Review by sysgear — APPROVED** [review]
Impressive work

**Review by dankositzke — COMMENTED** [review]
Thanks Royce for the formatting catch. Updated to PEP8 now and using 4 spaces instead of 2.

**Review by nhockcuncon77 — APPROVED** [review]
It looks awesome Dan. Thank you for your sharing.

**Review by jinjahninjah — APPROVED** [review]
Nice! Looks great!

**Review by Cole-Richards — APPROVED** [review]
I really like your inclusion of Euclidean distance model in this notebook. The explanation and visual were very helpful in understanding how it worked. 
Furthermore, it looks like the work you put into further explanation and modeling was thorough.

**Review by Katerynapass — APPROVED** [review]
looks nice! Great job!

**Review by mattclibanoff — APPROVED** [review]
Amazing additions to our model. I love how clean the output is.

**Pull request merged**
