### PR TITLE
Roberts/Mock data version 2

### PR DESCRIPTION
**Pull request by jinjahninjah**
## Description

Matt and I worked on making the mock data more relevant for the task at hand. We discovered at the stakeholder meeting that the matching process is relatively simple: the exp_level and skills(tech_stack) are used primarily, with other features like time zone, gender, general interests are used as a secondary matching feature.

### Loom Video:
https://www.loom.com/share/98a98d86ac544ed5b201a6351800943b

### Co-Author:
Matt Clibanoff
 
## Type of change

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by BrokenShell — APPROVED** [review]
This is good, you might want to add names to the mentor objects.

**Review by dankositzke — APPROVED** [review]
Awesome - the comprehensiveness of the Mentee dataframe is on point

**Comment by NigelClinton** [comment]
Looks great! I think the additional fields will help the matching process.

**Review by Katerynapass — APPROVED** [review]
It looks really good!

**Pull request merged**
