### PR TITLE
Implemented random datetime generator - ticket BL-681

### PR DESCRIPTION
**Pull request by woodbenwood**
## Description

Implemented a more streamlined random datetime generator with a single import line. Fixed an earlier PR issue that had a merge conflict.

Fixes # (issue)

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by woodbenwood** [comment]
After staggering party losses we abandoned the Quest for the Random Datetime and just implemented a random datetime generator with a single import line. (Fixed an earlier PR issue that had a merge conflict.)
[The Loom of our Misfortune](https://www.loom.com/share/14d93b9962844ea19a27704d113c0727)

**Comment by woodbenwood** [comment]
Hopefully this will get a Jira ticket soon, will update when/if

**Review by L0lbrich — APPROVED** [review]
Looks like this function will be used across the app, well done!

**Comment by ErinNC** [comment]
This is much nicer than separate generators with different implementations for timestamps. It's a great solution for this period of time while we still have mock data. Good work!

**Review by ErinNC — APPROVED** [review]
This is much nicer than separate generators with different implementations for timestamps. It's a great solution for this period of time while we still have mock data. Good work!

**Pull request merged**
