### PR TITLE
Two subjects: on 1/25, suggest use of K-mean clustering for mentor-mentee matching; on 1/20, Idea as question for mentor and mentee matching before stake holder meeting on 1/19

### PR DESCRIPTION
**Pull request by sysgear**
Two subjects: 
on 1/25, suggest use of K-mean clustering for mentor-mentee matching; 

on 1/20, Idea as question for mentor and mentee matching before stake holder meeting on 1/19
The idea in the notebook meant to ask the question in the stake holder meeting 1/19: Using a list of job description as career goal list for mentee to choose one. Each job description, career goal,  has the languages  skill required.  This pull request sent later than the stake holder meeting due to some technical difficulty not resolved in time.

Video recorded from zoom:
https://user-images.githubusercontent.com/86933356/151263988-6c99c47b-41f5-4274-b516-56324ebaf67a.mp4

### CODE REVIEW

**Review by LynnerKevin — APPROVED** [review]

**Review by LynnerKevin — APPROVED** [review]

**Review by dankositzke — CHANGES_REQUESTED** [review]
Hi Arthur - I like your idea about matching mentees and mentors based on their career goals and also the article link so mentees can choose a path. When I tried to run the notebook, there are a few cells that can be changed:

- code cell 1: curly brackets surrounding the second mentee
- code cell 2: curly brackets surrounding the second mentor
- code cell 3 line 4: "career" 
- code cell 3 line 5: closing parenthesis for the print statement

After changing those things it looks good

**Review by xianshiw — APPROVED** [review]

**Review by jinjahninjah — APPROVED** [review]
Looks good! For a simple matching, this works well; however, if the data is more complex or there are no more mentors to match with, it might have some issues. Still great work! 😄

**Comment by BrokenShell** [comment]
Confirmed Syntax Errors
> * code cell 1: curly brackets surrounding the second mentee
> * code cell 2: curly brackets surrounding the second mentor
> * code cell 3 line 4: "career" -> "career goal"
> * code cell 3 line 5: closing parenthesis for the print statement

Come see me if you need a hand fixing these!!!

**Review by Katerynapass — APPROVED** [review]
Good job overall!

**Review by dankositzke — APPROVED** [review]
Looks good!

**Comment by NigelClinton** [comment]
Looks great!

**Review by mattclibanoff — COMMENTED** [review]
This is an interesting way to break up Mentees. This could be an interesting way to pair mentors and mentees if we're aren't going for anything overly-specific.

**Pull request merged**
