### PR TITLE
Created a notebook that web scrapes Indeed job postings

### PR DESCRIPTION
**Pull request by Lopez-John**
## Description

Adds a notebook that web scrapes the Indeed website and returns CSVs :

Brogan Stich, Eisenhower Lancheros, and Dylan Budnick helped to create this notebook

https://www.loom.com/embed/f4bb4bb364ab4f3bae40557fe6cfe177

## Type of change

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by jinjahninjah — CHANGES_REQUESTED** [review]
Great work y'all!! I'm very excited to see this implemented in the app. The only changes is just remove the boilerplate code in your PR description and it should be good to go 👍

**Comment by Lopez-John** [comment]
Removed boilerplate code

**Review by jinjahninjah — APPROVED** [review]

**Comment by dylanbud** [comment]
We need to refactor this to use a different website -- Indeed's TOS does not allow for scraping of data. _"Use of any automated system or software, whether operated by a third party or otherwise, to extract data from the Site (such as screen scraping, crawling, reproducing, duplicating, copying, selling, trading or reselling) is prohibited. Publisher agrees that it is solely responsible for (and that Indeed has no responsibility or liability to it or to any third party for) any breach of Publisher’s obligations under these IPP Terms and for any consequences (including any loss or damage which Indeed may suffer) of any such breach."_ -- https://www.indeed.com/legal#publishers

**Comment by paulstgermain** [comment]
> We need to refactor this to use a different website -- Indeed's TOS does not allow for scraping of data. _"Use of any automated system or software, whether operated by a third party or otherwise, to extract data from the Site (such as screen scraping, crawling, reproducing, duplicating, copying, selling, trading or reselling) is prohibited. Publisher agrees that it is solely responsible for (and that Indeed has no responsibility or liability to it or to any third party for) any breach of Publisher’s obligations under these IPP Terms and for any consequences (including any loss or damage which Indeed may suffer) of any such breach."_ -- https://www.indeed.com/legal#publishers

Considering Dylan's comment above, I'm going to go ahead and mark this as needing changes for the time being - let's revisit and rework this to scrape a different site! Excellent work to build upon, though!

**Review by paulstgermain — CHANGES_REQUESTED** [review]
See my comment above!

**Comment by Lopez-John** [comment]
Correct a few commit issues with this branch and added language to the Indeed web scraper notebook saying its use violated Indeed's TOS

**Review by BobbyWilt — APPROVED** [review]

**Review by paulstgermain — APPROVED** [review]

**Pull request merged**
