### PR TITLE
Added exception handler to FastAPI

### PR DESCRIPTION
**Pull request by ulloa**
## Description

Added exception handler for FastAPI. This can be extended in the future and just is more laying the groundwork for more advanced error handling. Certain requests, when there is an invalid collection would return responses with body in text/plain format. Now as far as i know, all requests will have a response with a  body content-type: application/json.

Also, some style changes were included, specifically switching some single quotes to double quotes.

Fixes # [Trello issue](https://trello.com/c/jMpB1KTd)
Contributors: @sirivennelavempati @Annapurnaj91 @rodricobsanchez 

https://www.loom.com/share/8278608960c04fc1a4e648f7ffd66acc

## Type of change

- [x] Bug fix

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Annapurnaj91 — APPROVED** [review]
Good way to handle exceptions.

**Review by archana062031 — APPROVED** [review]
Looks good to me!!

**Review by OlatomiAdigun — APPROVED** [review]
Good one. Will surely be useful to handle execeptions

**Review by ChristineWangcy — APPROVED** [review]
Good one!

**Review by ZacharyRock — APPROVED** [review]
Good groundwork for an important feature, video explanation was simple, short, and easy to understand.

**Review by ev-horrosh — APPROVED** [review]
great ground to follow

**Review by jinjahninjah — APPROVED** [review]
Looks great! Looking forward to Web's feedback!

**Pull request merged**
