### PR TITLE
Created 'Mentee_Attrition' notebook to predict how many mentees will …

### PR DESCRIPTION
**Pull request by dankositzke**
## Description

Created 'Mentee_Attrition' notebook to predict how many mentees will leave in a given month.

## Type of change

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

https://www.loom.com/share/3ec7d47937114ad9a65081cec8bb04ed

### CODE REVIEW

**Review by Cole-Richards — APPROVED** [review]
I REALLY like this idea. I think it is a mechanism that, when fleshed out, can help underdog devs manage their resources (mentors) more efficiently. 

Good idea Dan!

**Review by mattclibanoff — APPROVED** [review]
This is genius. I'm sure there are some sensitivity issues here and it might be best to pitch this idea lightly, but overall I think predicting wash-out rate is a great move. It solves a problem Underdog Devs doesn't know it has/should be incredibly useful when used in conjunction with more human methods of review.

**Review by Katerynapass — APPROVED** [review]
I love the idea predicting how many mentees will leave and I think it would be very useful. Great job!

**Review by nhockcuncon77 — APPROVED** [review]
This idea is so useful and practical. I love the way how you explain that.

**Comment by LynnerKevin** [comment]
Looks interesting as another bit of information that we can look into, though I would caution against trying to predict how long a particular person will stay as that could cause behavioral changes in the mentors

**Comment by rodricobsanchez** [comment]
I like the idea of this approach I would of added more parameters in generating mock data, such as 'missed_sessions', 'total_sessions_attended', etc

**Review by Annapurnaj91 — APPROVED** [review]
Nice Idea Dan. That was a nice approach for predicting the number of mentee leaving

**Review by LynnerKevin — APPROVED** [review]
Cool idea, though I would caution about what you expect them to do with this information.

**Pull request merged**
