### PR TITLE
Matcher update

### PR DESCRIPTION
**Pull request by bradwbaker**
## Description

Updates to the MatcherSortSearch Class:

-  Removed unused random import (sample)
-  Removed mentee industry knowledge 
-  Changed mentor industry knowledge to not mentor industry knowledge for sorting

## Type of change

- [x] Bug fix

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

https://www.loom.com/share/f1e948d670a449fe90e1cc8557895b6a

### CODE REVIEW

**Review by fabiolavelasco — APPROVED** [review]
Thank you for these changes!

**Comment by bradwbaker** [comment]
https://www.loom.com/share/f1e948d670a449fe90e1cc8557895b6a

**Review by jinjahninjah — APPROVED** [review]
:shipit:

**Comment by Kseniyapl** [comment]
Here is a python algorithm!

**Pull request merged**
