### PR TITLE
add calendly research notebook

### PR DESCRIPTION
**Pull request by ev-horrosh**
Calendy API research to see what data is available
[quick video](https://www.loom.com/share/0c45ba469c4e4c91b83f8d2dee5e9720)
contributors: @archana062031 @Annapurnaj91 @mktran0417 
- [x] Notebook

[trello card](https://trello.com/c/2xCnlYNQ)
## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by MichaelJP-DS — APPROVED** [review]
Nice work Ev...great start on an interesting feature.  Bonus points for the Loom recording!

**Review by archana062031 — APPROVED** [review]
Code looks clean with detailed description!!

**Comment by rodricobsanchez** [comment]
Awesome this is some great research and will serve the next group of people well. I hope to see this implemented into the website in the future!

**Review by Annapurnaj91 — APPROVED** [review]
This research will be so useful going forward to do analysis. The code follows the pep8 and is easily understandable.

**Review by RylandGomez — APPROVED** [review]
Useful exploration of Calendly API usage, with easy to understand accompanying video. Will be useful for future cohorts as they think about integrating Calendly.

**Review by sirivennelavempati — APPROVED** [review]
Looks good to me with detailed video presentation.

**Review by mktran0417 — APPROVED** [review]
After the changes we made together I'm confident in saying that the code is good! Nice work with looking into the Calendly API.

**Pull request merged**
