### PR TITLE
Create McGraw_Papenburg_Notebook.ipynb

### PR DESCRIPTION
**Pull request by jonathan-mcgraw**
## Description

Fulfilling a feature request for the prediction of whether or not an individual within the database will require financial aid. The current output (within a separate dataframe) produces a probabilistic ratio of this variable given mock data reflecting the current database.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.
- [x] New feature

## Checklist:

- [ ] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [ ] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

## Pair-Programming
Who you paired with: Nicholas Papenburg
What pairing method(s) you used: Driver-navigator
How did it go? What did you learn?: It went well. We learned that creating mock data can be extremely useful when generating potential scripts.

Loom Video: https://www.loom.com/share/9e8286e108d04ea99c4bdb44fe29c0c7

### CODE REVIEW

**Comment by yefim-g** [comment]
I think everything for the most part looks good, the Loom video definitely helped. One suggestion: maybe add a docstring to the "Create_table" function to help align more with PEP8, but that's just a minute detail.

**Review by MichaelJP-DS — APPROVED** [review]
Agree that a docstring for Create_table would be helpful.  Nice additional feature.

**Review by yefim-g — APPROVED** [review]
I think everything for the most part looks good, the Loom video definitely helped. One suggestion: maybe add a docstring to the "Create_table" function to help align more with PEP8, but that's just a minute detail.

(Readding this because I forgot to approve it)

**Comment by jonathan-mcgraw** [comment]
Docstring has been added for the Create_table() function

**Comment by DagimB** [comment]
Fixed some PEP8 issues but really good otherwise!

**Review by SheebaHashmi — COMMENTED** [review]
Looks great! Great job everyone.

**Review by BakerJr1904 — COMMENTED** [review]
Great job with HTML, You guys rock!!

**Review by DagimB — COMMENTED** [review]
I tried to commit some PEP8 changes for spaces between operators in cell 3 and wrapping lines for too long of a line in cell 5

**Review by AustinJamesWolff — APPROVED** [review]
The notebook runs correctly and flake8 did not detect any PEP8 errors. The notebook is clear  on exactly what it's doing. Great work!

**Pull request merged**
