### PR TITLE
deletes some dead code, bumps the api version

### PR DESCRIPTION
**Pull request by BrokenShell**
## Description
Deletes several outdated endpoints. We worked on this as a team in Workshop.

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by sayerjk — DISMISSED** [review]
Good update to api.py. Removes un-used endpoints and adds some comments for clarity, making the file easier to interpret for newcomers, and clearer with its intent and functionality.

**Review by sspradling78 — APPROVED** [review]
I approve of these changes, a definite improvement. Clean too.

**Review by opeterschmidt — DISMISSED** [review]
A much-needed tidying up for the API. Prevents dirty data from getting added to our DB and makes things easier to understand for project newcomers.

**Review by rogerfvieira — DISMISSED** [review]
Codebase is much cleaner, making it much easier to shift through and make improvements to useful code.

**Review by annakoduru6 — DISMISSED** [review]
Looks much cleaner and easier to read. Good eye!

**Review by jsgersing — APPROVED** [review]
Way to shake that tree! Thoughtful removal of dead code and captures the api version update to boot.

**Review by ad-victoriam-101 — APPROVED** [review]
Looks good, Glad we migrated to spacy.

**Review by bradwbaker — APPROVED** [review]
Good changes to the API, removes unused endpoints and cleans up the code a lot making it easier to read.

**Review by L0lbrich — APPROVED** [review]

**Pull request merged**
