### PR TITLE
Update/adding docstrings

### PR DESCRIPTION
**Pull request by RylandGomez**
## Description

Changes are (hopefully) straightforward documentation of the various python files within the app folder. Some may want to be fleshed out more, and this documentation will likely change for some of the codebase as it grows and adapts to future ideas. Will convert from draft to actual PR once able to record Loom video.
The purpose of this PR is to support codebase comprehension, __doc__ implementation, assist debugging, facilitate IDE hinting tools, and catalog the purpose and functionality of our code on the DS side of things.

Contributors:
Ryland Gomez
Mohamed Mosaed

# These docstrings help future developers with IDE hints as well as offers further documentation within the Swagger UI. Having more detailed documentation will also help us analyze functionality and address potential issues; past, present, and future.

[Video Overview](https://www.loom.com/share/4d3805a6d7fa4424a86a17f5f1226a63)
[Trello Card](https://trello.com/c/ZJ83yBk7)

- [x] New (developer) feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by rodricobsanchez** [comment]
awesome this is super helpful for the future groups

**Review by jinjahninjah — APPROVED** [review]
Looks great Ryland! Thanks for adding the documentation! 😸

**Review by sirivennelavempati — APPROVED** [review]
Thanks for adding the docstrings.

**Review by Annapurnaj91 — APPROVED** [review]
Everything looks good for me.

**Pull request merged**
