### PR TITLE
Interpreter, and endpoint, for a proposed inter-API communication language

### PR DESCRIPTION
**Pull request by jonathan-mcgraw**
## Description

Proposition for the integration of a simple programming language, which can be used alongside the respective default language, for intuitive, custom, and efficient cross-api communication. This integration is in the process of being implemented on the backend by Maxwell Johnson, and on the frontend by Brittni Karat.

## Type of change

Please delete options that are not relevant.

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

Loom: https://www.loom.com/share/ebd6310362934ab8b8dfbbd64865d9ec

### CODE REVIEW

**Review by justinpeisker — APPROVED** [review]
What a great tool to ensure consistency in cross-API communication.  I appreciate your innovative approach to this!

**Review by BrittniKarat — APPROVED** [review]
This should lead to teams being able to take ownership of the entire process from frontend, backend, and DS simultaneously. Having a common language will make it easy to sync and standardize processes. Great find, Jonathon

**Comment by mktran0417** [comment]
Truly the innovation we needed.

**Review by WaylayOvercast — APPROVED** [review]
Absolutely outstanding, only 8 characters and any others are not interpreted, meaning you literally cant mess it up! good find, this language uses a compiler that would only take up 240 bytes!

**Review by mgrohnke — APPROVED** [review]
Great work on this! Loom video explains everything well!

**Review by hollberg — APPROVED** [review]
Such a great idea to embed a Turing-complete endpoint into the API. This could potentially eliminate the need to develop any additional code for this project, since any new functionality can simply be embedded in the headers to this endpoint. April 1st 2022 may go down in history as the last PR ever committed to this project!

**Comment by BrokenShell** [comment]
This is awesome! But no, just no.

**Pull request closed without merging**
