### PR TITLE
add responses schema

### LINKED ISSUE #160: add schema for responses collection
The responses collection currently has no schema validation in the schema.py script. All that is needed is a reponses field, keeping the mentee_id anonymous seems like the best move.

### PR DESCRIPTION
**Pull request by rogerfvieira**
very small update to the schema.py script, responses collection was missing schema validation

## Description

Noticed that the responses collection had no schema so I added it

Fixes #160

## Type of change

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

https://www.loom.com/share/0e6dd5e68e8c40bfa633d256a6410eba

### CODE REVIEW

**Review by annakoduru6 — APPROVED** [review]
Thanks for catching that! I'm not sure if it's supposed to be the same thing as Feedback, but it's still good to have everything copied over before we decided on anything.

**Review by sspradling78 — APPROVED** [review]
Nice catch

**Review by marthabg — CHANGES_REQUESTED** [review]
I might be out of the loop here but Responses is when a mentee answers on the intake form/application what they want to get out of Underdogs correct? If this is the case I'm wondering if Responses is okay being it's own collection or if it is supposed to be listed under the Mentee collection as an input. If not, shouldn't it be associated with the mentee who wrote it so that their needs are communicated with Admin about what it is they want? Maybe a conversation was already held around this and I was unaware. Let me know and I can change the status to approve!

**Review by sayerjk — CHANGES_REQUESTED** [review]
@BrokenShell Requesting review because I recall a session where you mentioned not needing to store `responses`. I can't recall if that was here or elsewhere and want to clarify. Otherwise, this is a sufficient schema for storing responses.

@ anyone — To reiterate— these are responses from mentees about what they are looking for from the program/community, correct? Maybe this info could be added as a docstring?

**Comment by rogerfvieira** [comment]
@ sayerjk , true. I don't know if the responses will stay in its own collection in the near future, if it is even stored anywhere to begin with. Not sure what to do next.

**Comment by zdravoj** [comment]
If this is related to Jira ticket BL-450 (database migration), then this PR is worthwhile. We were moving tables over from Postgres but we didn't consider the responses collection which was part of the database, but was not included in the schema file originally.

I'm still not sure how the responses collection was added without a class in schema.py. That's probably something to look into before we push this.

Regardless, we'll need to be ready to pull those responses out of the database and save them somewhere (probably a general text file) before we scrub the database.

**Comment by sayerjk** [comment]
> Regardless, we'll need to be ready to pull those responses out of the database and save them somewhere (probably a general text file) before we scrub the database.

I think you can create collections via `api.py` currently. And yes I agree we should have it if we need it.

**Comment by BrokenShell** [comment]
I believe the response collection should actually be a field on the Mentee object, as it is part of the intake form.

**Comment by sayerjk** [comment]
> 

I assume that would mean adjustments to [this other PR](https://github.com/BloomTech-Labs/underdog-devs-ds-a/pull/164)?

**Comment by sayerjk** [comment]
Is anyone else getting errors with the the spacy model `en_core_web_sm` when you run this endpoint point (`/responses_analysis`) from either the current `main` branch or the `responses_schema` branches? This might need some debugging. 

image

**Pull request closed without merging**
