### PR TITLE
Adding diagram rs

### PR DESCRIPTION
**Pull request by rodricobsanchez**
## Description
I'm adding model diagram for the README to share how the matching process works visually, so that non data scientists can understand it

https://trello.com/c/GDiF9CPC/208-as-a-data-scientist-i-want-to-share-the-how-the-matching-process-works-visually-so-that-non-data-scientists-can-understand-it

https://www.loom.com/share/bd151074a0474061be80aed6afe3198a

## Type of change
- [x] This change requires a documentation update

## Checklist:
- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by ChristineWangcy — APPROVED** [review]
Beautiful job! It looks good to me.

**Review by ulloa — APPROVED** [review]
Great

**Review by archana062031 — APPROVED** [review]
This architecture is amazing!!

**Review by sirivennelavempati — APPROVED** [review]
model architecture looks good

**Review by Annapurnaj91 — APPROVED** [review]
Nice model architecture

**Review by RylandGomez — APPROVED** [review]
Quality diagram, and the banner looks nice too! Simple, but very effective changes.

**Review by jinjahninjah — CHANGES_REQUESTED** [review]
Awesome job on the graphic everyone! It looks amazing! 

*This PR needs a video before it can merged*

Other than that, it looks great!

**Review by jinjahninjah — APPROVED** [review]

**Pull request merged**
