### PR TITLE
Knn Model with Collaborative Filtering

### PR DESCRIPTION
**Pull request by mktran0417**
## Description
https://www.loom.com/share/f2c0ee3c977d418fac414855bb4bceaa

Implemented a KNN model with collaborative filtering based on a randomly generated review matrix and compares the results to a base KNN model. The implementation requires further work but perhaps it will give others more ideas to play with when we have access to real data.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix
- [x ] New feature
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

Contributors - @MichaelJP-DS @mktran0417

### CODE REVIEW

**Comment by ChristineWangcy** [comment]
Excellent hard work, and thank you for sharing. I agree that a video of a walkthrough will make it easier to follow. I'm still investigating it.

**Review by LynnerKevin — APPROVED** [review]
What was the purpose of the "first" handle that you removed here? Was it meant to just return a random entry from the given collection?

**Review by paulstgermain — CHANGES_REQUESTED** [review]
This PR needs a Loom/video walkthrough of the changes made before I can merge it! 😱

**Comment by rodricobsanchez** [comment]
Just needs the video and its a yes from me!

**Review by OlatomiAdigun — APPROVED** [review]
Nice. Surely a great foundation on which future model can be built on

**Pull request closed without merging**
