### PR TITLE
Updated ML Model and MongoDB Class

### PR DESCRIPTION
**Pull request by ulloa**
## Description

Updates to the model were made to improve results of matching algorithm. Sorting now considers pair programming desire and industry knowledge, in addition to experience level and subject. 

Several variable names were changed to have consistency with the Underdog Devs backend (mentee_id -> profile_id, user_id -> profile_id).

_connect for MongoDB class is more internal functionality. A get_collection method was added to replace the flexibility _connect had.

Data Generator scripts now create more complete Mentors and Mentee data. UUID format is used to generate `profile_id`.

Fixes # [Trello issue](https://trello.com/c/TnuU2T9f)

[Explanation video](https://www.loom.com/share/2d4fa669e03b4d5e825d9f83a39fe7fe)
## Type of change

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

Contributors: @BrokenShell @ulloa @ev-horrosh @LynnerKevin @RylandGomez @mktran0417 @Annapurnaj91 @archana062031 @rodricobsanchez @ZacharyRock @sirivennelavempati @MichaelJP-DS @ChristineWangcy @OlatomiAdigun

### CODE REVIEW

**Review by rodricobsanchez — APPROVED** [review]
Its about time this gets updated! Code is clean and clear!

**Review by sirivennelavempati — APPROVED** [review]
Nice and Detailed video explanation.

**Review by ev-horrosh — APPROVED** [review]
matching is ready for mvp. I was wondering if it'd make sense to output matches in a full document as opposed to just ids for the mentors?

**Comment by ulloa** [comment]
> matching is ready for mvp. I was wondering if it'd make sense to output matches in a full document as opposed to just ids for the mentors?

It might be a good idea if that's what the backend team needs. However, not sure if they are just going to use the ids to query their own db instead.

**Review by Annapurnaj91 — APPROVED** [review]
Everything looks good for me

**Review by archana062031 — APPROVED** [review]
Code looks clean with updated docstrings!!

**Review by RylandGomez — APPROVED** [review]
Overall, straightforward changes that I can certainly agree with. Seems to all be implemented with proper PEP8, cleaning up some preexisting formatting mistakes. Big fan of the input example for the API endpoint.

**Review by mktran0417 — APPROVED** [review]
Looks good! I don't see any glaring issues. Nice example in the docstring as well.

**Pull request merged**
