### PR TITLE
updates feedback generator

### PR DESCRIPTION
**Pull request by BrokenShell**
## Description
- Updates Feedback Generator
- Adds Feedback MongoDB Collection - NLP friendly data!

## Contributors
Robert Sharp
Dylan Budnick
Roberto Gomez
Zachary Rock
Austin Wolff
Matt Grohnke
Michael Petrus
John Baker
Dagim Bantikassegn
Yefim Gorodnitskiy
Jonathan McGraw
Nicholas Papenburg
Mitch Hollberg
Brittni Karat

## Type of change
- [x] New feature

## Checklist:
- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by yefim-g — APPROVED** [review]
We went over the changes during DS Workshop. Everything looks great and there were definitely improvements made.

**Review by MichaelJP-DS — APPROVED** [review]
Nice workshop - updates look good!

**Review by jinjahninjah — APPROVED** [review]
:shipit:

**Comment by NPAPENBURG** [comment]
I was here for the Live workshop for this PR. This was a great way to clean up Feedback which ended up helping me out with my own PR.

**Review by ZacharyRock — APPROVED** [review]
This could also be a basis for generating a more generalized "meeting notes" mock db, since it is known the front/backend have been wanting to add that feature, it might give us additional avenues to pursue solutions.

**Review by DagimB — COMMENTED** [review]
I attended the workshop that went over and updates the feedback generator. It was really informative and helpful.

**Comment by itsmerobert12** [comment]
I attended the workshop that went over and updated the feedback generator. Robert was awesome and everybody else who contributed, I greatly appreciate all the information.

**Review by BakerJr1904 — COMMENTED** [review]
This was a smart change that will benefit us all.

**Pull request merged**
