### PR TITLE
Feature/ds32 meeting notes sentiment

### PR DESCRIPTION
**Pull request by hollberg**
## Description

Co-authored by:
@Zack-Quintana 
@MichaelJP-DS 
@hollberg 

Notebook illustrating lifecycle of defining a sentiment analysis function leveraging the Vader sentiment analysis toolkit.

Notebook queries all UnderDog Devs meeting contents, and updates meeting note text with mock data. Then feature engineers a new column in a DataFrame containing the net sentiment score for the meeting.

## Type of change

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

Loom video link:
https://www.loom.com/share/10c9ff9cc68040cabdd2d6877cfed9c7

### CODE REVIEW

**Review by jinjahninjah — CHANGES_REQUESTED** [review]
Great job everyone! This is definitely something that can be incorporated into the ```user_generators.py``` file if you can automate it. This will definitely lay the ground work for future releases dealing with the meeting ticket system. 

Just a couple quick things: 
- Remove the boilerplate code in the PR
- Add a Loom video describing what you are doing in your PR

And everything should be good to go 👍

**Comment by hollberg** [comment]
> 

Thanks for the feedback Royce. I've cleaned up the PR text and added a Loom link.

**Review by NPAPENBURG — APPROVED** [review]
This is a great start! You will have to factor in the function that is created for this already so their might need to be some slight tweaks down the line.

**Review by mgrohnke — APPROVED** [review]
This is great work.  Good work with addressing the requested changes as well.

**Review by jinjahninjah — APPROVED** [review]

**Pull request merged**
