### PR TITLE
BL-488 Feature/user_generators name update 

### PR DESCRIPTION
**Pull request by ErinNC**
Changed "user_generators.py" to "generators.py" and the two references of imports in seeds.py and api_testing.py because this file contains generators for collections other than just users

Fixes # [BL-497](https://bloomtechlabs.atlassian.net/browse/BL-497)

## Type of change

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

[Loom](https://www.loom.com/share/0c9ea1a6af9b4450ba108cae102fa81b)

### CODE REVIEW

**Comment by ErinNC** [comment]
Will record a loom video later today.

**Review by annakoduru6 — APPROVED** [review]
Simple fix, nice work

**Review by jsgersing — APPROVED** [review]
A name change that better aligns the name with what the file is, and the PR covers the appropriate bases.

**Review by opeterschmidt — CHANGES_REQUESTED** [review]
Code looks great! Provides necessary clarification of purpose of the generators.py file, as it generates multiple kinds of mock data, not just users. 

I believe the PR title should use the main Jira issue #, not the subtask # (so it can be properly linked there), and it looks like you’re missing the last bit of the PR description. Once those are updated this should be good to go!

**Review by opeterschmidt — APPROVED** [review]

**Review by CrisIV — APPROVED** [review]
A simple fix but important, better reflects the purpose of the generators.py file. Great work!

**Review by sayerjk — APPROVED** [review]
Good name adjustment for clarity. Accurate labels are key.

**Review by JoshuaPattonWeb — APPROVED** [review]
Easy change for readability and directory. Great thing to compile everything to one location so developers do not have to run around to find information of the same sort. Good job!

**Review by ad-victoriam-101 — APPROVED** [review]
Looks Good,

**Review by rogerfvieira — APPROVED** [review]
Cleaner file name, nice quick fix

**Review by willisbridges — COMMENTED** [review]
Quick and easy, thanks for doing this!

**Review by willisbridges — APPROVED** [review]

**Pull request merged**
