### PR TITLE
Bl 999 ds api integration tests

### PR DESCRIPTION
**Pull request by nikolayglushetskiy**
## Description
Created integration tests notebooks for API endpoints.
There are three notebook in tests dir, for proper integration tests , failed integration tests and matches endpoint integration tests.
If you have problem with import libraries: uncomment line in a first cell with `% cd ../`, run it once and comment it out again.
Notebooks should run without any errors, if you get an assertion error then you have some problem with API.

## Jira Ticket
https://bloomtechlabs.atlassian.net/browse/BL-999

## Type of Change
- [ ] Bug fix
- [x] New feature
- [ ] This change requires a documentation update

## Checklist
- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [ ] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

## Loom Video
https://www.loom.com/share/aab6ee21d22e41588d7ac9196398873f

### CODE REVIEW

**Review by zoebrantley — DISMISSED** [review]
This looks great!!! Love the formatting, easy and clean to read. 10/10

**Review by TophertheCoder — APPROVED** [review]
Great job! Error messages are clear and concise. Very easy to debug if they should arise. Clean and neat format as well.

**Review by zoebrantley — DISMISSED** [review]
Above review still applies. 10/10 work!

**Review by JeffDesch — DISMISSED** [review]
Tests are thorough and well-organized, definitely a big help when developing the new endpoints. Just a note when filling out the PR form to be careful to not leave spaces or use upper-case when filling in the check boxes, so the resulting markdown looks nicer.

**Review by zoebrantley — APPROVED** [review]
Above review still applies!

**Review by TophertheCoder — APPROVED** [review]
Previous review still holds. Nice work

**Review by allielcox — APPROVED** [review]

**Review by JeffDesch — APPROVED** [review]
Same as before: tests are thorough and well-organized, definitely a big help when developing the new endpoints.

**Pull request merged**
